# Generated by Django 3.1.5 on 2021-01-27 02:23

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_userplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='userplan',
            name='payment_list',
            field=models.ForeignKey(default=datetime.date(2021, 1, 27), on_delete=django.db.models.deletion.CASCADE, to='core.paymentlist', verbose_name='payment list'),
        ),
    ]
