# Generated by Django 3.1.5 on 2021-01-31 23:18

import core.models
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_quote'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentListMonth',
            fields=[
                ('paymentList_id', models.CharField(default=uuid.uuid4, max_length=255, primary_key=True, serialize=False, unique=True)),
                ('myList', models.TextField(default=core.models.payment_list, null=True)),
            ],
        ),
    ]
