# Generated by Django 3.1.5 on 2021-02-01 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_policy'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='customerId_oneinc',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
