# Generated by Django 3.1.5 on 2021-02-01 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20210201_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='active',
            field=models.BooleanField(db_index=True, default=False, verbose_name='active'),
        ),
    ]
