# Generated by Django 3.1.6 on 2021-02-04 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_quote_premium_cost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='policy',
            old_name='policy_paymentListMonth_number',
            new_name='paymentListMonth_number',
        ),
        migrations.RenameField(
            model_name='policy',
            old_name='policy_quote_number',
            new_name='quote_number',
        ),
        migrations.AddField(
            model_name='paymentlistmonth',
            name='quote_number',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.quote', verbose_name='quote'),
        ),
    ]
