# Generated by Django 3.1.6 on 2021-02-04 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20210204_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentlistmonth',
            name='quote_number',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.quote', verbose_name='quote'),
        ),
    ]
