# Generated by Django 3.1.6 on 2021-02-09 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20210204_2318'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='customerId_oneinc',
            new_name='token_oneinc',
        ),
    ]
